OrdererOrgs:
  - Name: Orderer
    Domain: drug-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: manufacturer
   Domain: manufacturer.drug-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: distributor
   Domain: distributor.drug-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: transporter
   Domain: transporter.drug-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
